### ISSUE TITLE
Unable to sign exportC transaction - Ledger Nano S Plus

### ISSUE THREAD

**Issue by mouradski** [flare-foundation/flare-stake-tool#21]
Hello, 

I get this error when I try to export some FLR to P-Chain : 

Device : Ledger Nano S Plus

`Version: 3.0.2

Using network: flare
Fetching account from ledger...
Creating export transaction...
Using fee of 0.00028075 FLR
Please review and sign the transaction on your ledger device...
Error: Can not sign message on ledger: Data is invalid : , code 27264`

The command I use 

`flare-stake-tool exportCP -a 1000000 --ledger`

**Comment by kuco23** [comment]
Hi, I assume you are using avalanche app on ledger. With that app only blind signing is possible, as it doesn't correctly parse flare's transaction details, so you should append `--blind` after each command.

Note that flare ledger app is still in development phase and the next version of flare-stake-tool will have `--blind`  flag set as default, with some security mitigations in place.

**Comment by mouradski** [comment]
yes, i'm using avalanche app, and yes, --blind param fixed the issue

thank you very much 🙏

**Comment by mouradski** [comment]
fixed in https://github.com/flare-foundation/flare-stake-tool/commit/5ee7e3442720fccd09d29c89322b3583983b09a4
